### ISSUE TITLE
Eigen version errors when trying to ./build.sh (g20 and Sophus need different versions)

### ISSUE THREAD

**Issue by anastaga** [UZ-SLAMLab/ORB_SLAM3#609]
I have met a series of errors trying to build orbslam3. I tried both this repo and the one found here https://github.com/nindanaoto/ORB_SLAM3 .

When trying to compile ORBSLAM3:
If I use an eigen version of < 3.3 (such as 3.2) i can compile g2o without any deprecation errors. 
On the other hand, Sophus needs eigen 3.3 to work as of find_pacakge(Eigen 3.3)   (though on the Readme file you mention it does work with Eigen 3.1 and higher.)
If I upgrade the system's version to Eigen 3.3 thought I meet many compilation errors with g2o (found in a plethora of github issues in this repo).

I tried installing 2 different versions of Eigen (3.2 and 3.4) and linked g2o to use 3.2 and Sophus to use 3.4 but as it seems, when building the ORBSLAM3/build, it seems like it calls Sophus and g2o again so it again have compilation errors depending on the version of Eigen i link the Cmakelists of ORBSLAM3.

Im asking if anyone managed to execute ./build.sh and ./build_ros.sh without any errors and if you can share any foolproof way to build it.

I tried both Ubuntu 18 and 20.
Using a plethora of Eigen versions ranging from 3.1 to 3.4
Pangolin (tested 2 versions, the latest and v0.5)
OpenCV 3.2.0

**Comment by Colorlucky** [comment]
Same Problem here...
